import './globals.css'
import { Inter } from 'next/font/google'
import * as React from 'react';
import PropTypes from 'prop-types';
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import CssBaseline from '@mui/material/CssBaseline';
import useScrollTrigger from '@mui/material/useScrollTrigger';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import ThemeRegistry from "@/mui/ThemeRegistry/ThemeRegistry";

function ElevationScroll(props) {
  const { children, window } = props;
  // Note that you normally won't need to set the window ref as useScrollTrigger
  // will default to window.
  // This is only being set here because the demo is in an iframe.
  const trigger = useScrollTrigger({
    disableHysteresis: true,
    threshold: 0,
    target: window ? window() : undefined,
  });

  return React.cloneElement(children, {
    elevation: trigger ? 4 : 0,
  });
}

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <ThemeRegistry options={{ key: "mui" }}>
      {/* <ElevationScroll {...props}> */}
        <AppBar>
          <Toolbar>
            <Typography variant="h5">
              Story-Craft
            </Typography>
          </Toolbar>
        </AppBar>
      {/* </ElevationScroll> */}
      <Toolbar />

        {children}
        </ThemeRegistry></body>
    </html>
  )
}
